flows:
  word_embeddings_flow:
    params:
      skill_sentences_dir: "outputs/sentence_classifier/data/skill_sentences/2021.08.16/textkernel-files/"
      token_len_threshold: 20
      output_dir: "outputs/skills_extraction/word_embeddings/data/"
  extract_skills:
    params:
      sentence_embeddings_dir: "outputs/skills_extraction/word_embeddings/data/2021.08.31/"
      prop_not_masked_threshold: 0.2
      mask_seq: "[MASK]"
      umap_n_neighbors: 10
      umap_min_dist: 0.0
      umap_random_state: 42
      umap_n_components: 2
      dbscan_eps: 0.01
      dbscan_min_samples: 3
      dir_sample_size: 30
      dir_sample_seed: 42
      sent_emb_sample_seed: 42
      sent_emb_sample_size:
      sentence_lengths_lower: 50
      sentence_lengths_upper: 100
      output_dir: "outputs/skills_extraction/extracted_skills/"
  name_skills:
    params:
      skill_sentences_path: "outputs/skills_extraction/extracted_skills/2021.11.05_sentences_skills_data.json"
      skills_path: "outputs/skills_extraction/extracted_skills/2021.11.05_skills_data.json"
      skills_embeds_path: "outputs/skills_extraction/reduced_embeddings/"
      mean_skills_embeds_path: "outputs/skills_extraction/extracted_skills/2021.11.05_skill_mean_embeddings.json"
      ngram: 3
      min_count: 1
      threshold: 0.15
      num_top_sent: 3
      output_dir: "outputs/skills_extraction/extracted_skills/"
  esco_mapper:
    params:
      esco_data_dir: "inputs/ESCO/v1.0.8/"
      esco_skills_file: "skills_en.csv"
      esco_lang_skills_file: "languageSkillsCollection_en.csv"
      esco_ict_esco_skills_file: "ictSkillsCollection_en.csv"
      esco_trans_esco_skills_file: "transversalSkillsCollection_en.csv"
      tk_skills_path: "outputs/skills_extraction/extracted_skills/2021.08.31_skills_data.json"
      output_dir: "outputs/skills_extraction/esco_maps/"
      map_similarity_score_threshold: 0.5
    run_id: 0
